# Configuration specific to Sonarr
# dry run: `docker compose run --rm recyclarr sync sonarr --preview`
sonarr:
  series:
    # Set the URL/API Key to your actual instance
    base_url: !secret sonarr_url
    api_key: !secret sonarr_api_key

    # Quality definitions from the guide to sync to Sonarr. Choices: series, anime
    quality_definition:
      type: series

    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    include:
      - template: web-1080p-v4
      - template: web-2160p-v4
      - template: anime-sonarr-v4

# Configuration specific to Radarr.
# dry run: `docker compose run --rm recyclarr sync radarr --preview`
radarr:
  movies:
    # Set the URL/API Key to your actual instance
    base_url: !secret radarr_url
    api_key: !secret radarr_api_key

    # Which quality definition in the guide to sync to Radarr. Only choice right now is 'movie'
    quality_definition:
      type: movie

    # Set to 'true' to automatically remove custom formats from Radarr when they are removed from
    # the guide or your configuration. This will NEVER delete custom formats you manually created!
    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    include:
      - template: remux-web-2160p
      - template: uhd-bluray-web