version: "2"
services:

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1026
      - PGID=101
      - VERSION=docker
      - TZ=Europe/London
    volumes:
      - /mnt/storage/config/plex:/config
      - /mnt/storage/tv:/tv
      - /mnt/storage/movies:/movies
      - /mnt/storage/music:/music
      - /mnt/storage/config/plex/transcode:/transcode
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
    volumes:
      - /mnt/storage/config/sonarr:/config
      - /mnt/storage/tv:/tv
      - /mnt/storage/downloads:/downloads
    ports:
      - 32784:8989
    restart: unless-stopped
    networks:
      home:

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
    volumes:
      - /mnt/storage/config/radarr:/config
      - /mnt/storage/movies:/movies
      - /mnt/storage/downloads:/downloads
    ports:
      - 32783:7878
    restart: unless-stopped
    networks:
      home:

  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
    volumes:
      - /mnt/storage/config/sabnzbd:/config
      - /mnt/storage/downloads:/downloads
      - /mnt/storage/downloads/incomplete:/incomplete-downloads #optional
    ports:
      - 32781:8080
      - 32782:9090
    restart: unless-stopped
    networks:
      home:
  
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /mnt/storage/config/deluge:/config
      - /mnt/storage/downloads:/downloads
    ports:
      - 32789:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      home:

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
    volumes:
      - /mnt/storage/config/lidarr:/config
      - /mnt/storage/music:/music
      - /mnt/storage/downloads:/downloads
    ports:
      - 32786:8686
    restart: unless-stopped
    networks:
      home:

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
    volumes:
      - /mnt/storage/config/prowlarr:/config
    ports:
      - 32787:9696
    restart: unless-stopped
    networks:
      home:

  iperf3:
    image: networkstatic/iperf3
    container_name: iperf3
    ports:
      - 5201:5201
    restart: unless-stopped
    command: -s
    networks:
      home:

  netdata:
    image: netdata/netdata
    container_name: netdata
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
    network_mode: host
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - /mnt/storage/config/netdata/config:/etc/netdata
      - /mnt/storage/config/netdata/data:/var/lib/netdata
      - /mnt/storage/config/netdata/cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/VERSION:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  home:
    driver: bridge