version: "2"
services:

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1026
      - PGID=101
      - VERSION=docker
      - TZ=Europe/London
    volumes:
      - /volume1/config/plex:/config
      - /volume1/tv:/tv
      - /volume1/movies:/movies
      - /volume1/music:/music
      - /volume1/config/plex/transcode:/transcode
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
    volumes:
      - /volume1/config/sonarr:/config
      - /volume1/tv:/tv
      - /volume1/downloads:/downloads
    ports:
      - 32784:8989
    restart: unless-stopped
    networks:
      home:

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
    volumes:
      - /volume1/config/radarr:/config
      - /volume1/movies:/movies
      - /volume1/downloads:/downloads
    ports:
      - 32783:7878
    restart: unless-stopped
    networks:
      home:

  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
    volumes:
      - /volume1/config/sabnzbd:/config
      - /volume1/downloads:/downloads
      - /volume1/downloads/incomplete:/incomplete-downloads #optional
    ports:
      - 32781:8080
      - 32782:9090
    restart: unless-stopped
    networks:
      home:
  
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /volume1/config/deluge:/config
      - /volume1/downloads:/downloads
    ports:
      - 32789:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      home:

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
    volumes:
      - /volume1/config/lidarr:/config
      - /volume1/music:/music
      - /volume1/downloads:/downloads
    ports:
      - 32786:8686
    restart: unless-stopped
    networks:
      home:

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/London
    volumes:
      - /volume1/config/prowlarr:/config
    ports:
      - 32787:9696
    restart: unless-stopped
    networks:
      home:

  iperf3:
    image: networkstatic/iperf3
    container_name: iperf3
    ports:
      - 5201:5201
    restart: unless-stopped
    command: -s
    networks:
      home:

networks:
  home:
    driver: bridge
