---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
- network:

        - pihole:
                href: http://pi.hole/admin/
                icon: pi-hole.svg
                widget:
                      type: pihole
                      url: http://pi.hole
