version: '2'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole
    hostname: pihole
    domainname: home
    mac_address: d0:ca:ab:cd:ef:01
    cap_add:
      - NET_ADMIN
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    environment:
      TZ: 'Europe/London'
      ServerIP: 192.168.1.201
      WEBPASSWORD: ""
      VIRTUAL_HOST: pihole.home
    volumes:
      - './overwrite_resolv.conf:/etc/resolv.conf'
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
